# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-28 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=128)),
                ('mft_date', models.DateTimeField(default=datetime.datetime(2018, 7, 28, 7, 53, 15, 388331))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=128)),
                ('cat_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('product_price', models.IntegerField()),
                ('product_color', models.CharField(max_length=128)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.Brand')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.Category')),
            ],
        ),
    ]
