# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='mft_date',
            field=models.CharField(max_length=128),
        ),
    ]
